### ISSUE TITLE
Class is not autoloaded

### ISSUE THREAD

**Issue by goblindegook** [nekojira/wp-requirements#3]
Hi,

I've been trying to use your project in my plugins with Composer, but for some reason the `WP_Requirements` class is not autoloaded.

For example, this example code triggers an error on activation:

``` php
<?php
if ( ! defined( 'WPINC' ) ) {
    die;
}

if ( version_compare( PHP_VERSION, '5.3.0' ) === -1 ) {
    require_once 'vendor/autoload_52.php';
} else {
    require_once 'vendor/autoload.php';
}

$example_requirements = new WP_Requirements(
    'Example',
    plugin_basename( __FILE__ ),
    array(
        'PHP'        => '8.3.2',
        'WordPress'  => '6.0.0',
        'Extensions' => array(
            'future',
        ),
    )
);

if ( $example_requirements->pass() === false ) {
    $example_requirements->halt();
    return;
}
```

The error:

> Plugin could not be activated because it triggered a fatal error.
> Fatal error: Class 'WP_Requirements' not found in ...

The only way I could make it work is by manually adding this line:

```
require_once 'vendor/nekojira/wp-requirements/src/wp-requirements.php';
```

I feel like I'm missing something because your other plugins seem to function just fine with similar logic. Any ideas?

**Comment by unfulvio** [comment]
are you using https://bitbucket.org/xrstf/composer-php52?

check the contents of your composer /vendor libraries to see if the class is included or not

I stopped supporting this class since WordPress offers no solution to package management and the possibilities of package collisions are just too high

you'd be better off copying the class and/or namespacing it to make it unique

**Comment by goblindegook** [comment]
Yes, copying the class to my plugin is what I ended up doing.

The `xrstf/composer-php52` package was installed and your class was present in the `vendor` directory, but it still wasn't autoloaded when instantiated. I would guess the `class_exists()` check is interfering with the autoloader somehow, but I didn't look further.

Anyway, copying the class works for me, and it does its thing well. Thanks!
